# Generated by Django 4.2.9 on 2024-01-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolio_caption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedaInfo',
            new_name='SocialMediaInfo',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
